<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>com.lrj.commerce</groupId><artifactId>commerce-platform</artifactId><version>0.1.0-SNAPSHOT</version></parent><artifactId>inventory</artifactId><dependencies><dependency><groupId>com.lrj.commerce</groupId><artifactId>platform-runtime</artifactId><version>${project.version}</version></dependency><dependency><groupId>com.lrj.commerce</groupId><artifactId>catalog</artifactId><version>${project.version}</version></dependency><dependency><groupId>com.lrj.commerce</groupId><artifactId>store</artifactId><version>${project.version}</version></dependency></dependencies><build><plugins><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-surefire-plugin</artifactId><configuration><failIfNoTests>false</failIfNoTests></configuration></plugin></plugins></build></project>
