CREATE TABLE journey_definition (
 tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识',
 journey_id VARCHAR(64) NOT NULL COMMENT '旅程标识',
 version BIGINT NOT NULL COMMENT '不可变内容版本',
 store_id VARCHAR(64) NOT NULL COMMENT '归属店铺',
 trigger_type VARCHAR(32) NOT NULL COMMENT '手工或支付事实触发',
 valid_from TIMESTAMP(6) NOT NULL COMMENT '允许入组开始UTC时间',
 valid_to TIMESTAMP(6) NOT NULL COMMENT '允许入组结束UTC时间',
 definition_json JSON NOT NULL COMMENT '已验证的有向无环节点图',
 status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '审批发布状态',
 lock_version BIGINT NOT NULL DEFAULT 0 COMMENT '并发控制版本',
 published_id VARCHAR(64) GENERATED ALWAYS AS (CASE WHEN status='PUBLISHED' THEN journey_id ELSE NULL END) STORED COMMENT '同旅程仅允许一个发布版本',
 PRIMARY KEY(tenant_id,journey_id,version),
 UNIQUE KEY uk_journey_published(tenant_id,published_id),
 KEY idx_journey_trigger(tenant_id,store_id,status,trigger_type),
 CONSTRAINT ck_journey_definition CHECK(version>0 AND valid_to>valid_from AND status IN ('DRAFT','IN_REVIEW','APPROVED','REJECTED','PUBLISHED','PAUSED') AND trigger_type IN ('MANUAL','ORDER_PAID'))
) COMMENT='不可变营销旅程版本与审批状态';
CREATE TABLE journey_instance (
 tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识',
 instance_id VARCHAR(64) NOT NULL COMMENT '持久实例标识',
 journey_id VARCHAR(64) NOT NULL COMMENT '引用旅程标识',
 journey_version BIGINT NOT NULL COMMENT '冻结内容版本',
 member_id VARCHAR(64) NOT NULL COMMENT '入组会员',
 order_id VARCHAR(64) NULL COMMENT '可信来源订单，手工入组为空',
 event_key VARCHAR(64) NOT NULL COMMENT '触发事实去重键',
 current_node VARCHAR(64) NOT NULL COMMENT '下一个待执行节点',
 status VARCHAR(32) NOT NULL DEFAULT 'RUNNING' COMMENT '实例执行状态',
 due_at TIMESTAMP(6) NOT NULL COMMENT '下次执行UTC时间',
 deadline TIMESTAMP(6) NOT NULL COMMENT '实例绝对截止UTC时间',
 steps INT NOT NULL DEFAULT 0 COMMENT '已提交节点数',
 attempts INT NOT NULL DEFAULT 0 COMMENT '当前节点连续失败次数',
 result VARCHAR(32) NULL COMMENT '终止或失败原因码，无敏感详情',
 version BIGINT NOT NULL DEFAULT 0 COMMENT '并发更新版本',
 PRIMARY KEY(tenant_id,instance_id),
 UNIQUE KEY uk_journey_entry(tenant_id,journey_id,journey_version,event_key),
 KEY idx_journey_due(tenant_id,status,due_at,instance_id),
 KEY idx_journey_deadline(tenant_id,status,deadline),
 KEY idx_journey_order(tenant_id,order_id,instance_id),
 KEY idx_journey_member(tenant_id,member_id,instance_id),
 CONSTRAINT ck_journey_instance CHECK(status IN ('RUNNING','WAITING','ISOLATED','COMPLETED','CANCELLED','TIMED_OUT') AND steps BETWEEN 0 AND 33 AND attempts BETWEEN 0 AND 5)
) COMMENT='可恢复营销旅程检查点';
CREATE TABLE journey_notification (
 tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识',
 notification_id VARCHAR(64) NOT NULL COMMENT '站内信标识',
 instance_id VARCHAR(64) NOT NULL COMMENT '来源实例',
 node_id VARCHAR(64) NOT NULL COMMENT '来源节点',
 member_id VARCHAR(64) NOT NULL COMMENT '收件会员',
 title VARCHAR(128) NOT NULL COMMENT '纯文本标题',
 body VARCHAR(1000) NOT NULL COMMENT '纯文本内容',
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建UTC时间',
 PRIMARY KEY(tenant_id,notification_id),
 UNIQUE KEY uk_journey_notification(tenant_id,instance_id,node_id),
 KEY idx_notification_member(tenant_id,member_id,notification_id)
) COMMENT='旅程站内触达持久收件箱';
