CREATE TABLE marketing_execution (
 tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户，所有执行读写必须带此作用域',
 order_id VARCHAR(64) NOT NULL COMMENT '触发参与的真实订单标识',
 campaign_id VARCHAR(64) NOT NULL COMMENT '固定活动标识',
 campaign_version BIGINT NOT NULL COMMENT '报价选中的不可变活动版本',
 quote_id VARCHAR(64) NOT NULL COMMENT '产生本次决定的报价快照标识',
 member_id VARCHAR(64) NOT NULL COMMENT '实际受益会员标识',
 store_id VARCHAR(64) NOT NULL COMMENT '实际成交店铺标识',
 rule_id VARCHAR(64) NULL COMMENT '已发布规则资产标识，内嵌规则为空',
 rule_version BIGINT NULL COMMENT '已发布规则资产版本，内嵌规则随活动版本',
 audience_id VARCHAR(64) NULL COMMENT '固定人群快照标识，无人群门槛为空',
 audience_version BIGINT NULL COMMENT '固定人群快照版本，无人群门槛为空',
 benefit_id VARCHAR(64) NULL COMMENT '内部CREDIT权益定义标识，纯优惠活动为空',
 benefit_version BIGINT NULL COMMENT '内部CREDIT权益定义版本，纯优惠活动为空',
 grant_id VARCHAR(64) NULL COMMENT '真实权益预留记录标识，纯优惠活动为空',
 discount_amount DECIMAL(14,2) NOT NULL COMMENT '选中活动在报价中计算的人民币优惠',
 reason_code VARCHAR(32) NOT NULL COMMENT '稳定决策原因码，当前选中活动为ELIGIBLE',
 status VARCHAR(24) NOT NULL COMMENT 'RESERVED、GRANT_REQUESTED、GRANTED、APPLIED或RELEASED',
 evaluated_at TIMESTAMP(3) NOT NULL COMMENT '报价规则显式评价时间UTC',
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '参与记录创建时间UTC',
 updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最近状态提交时间UTC',
 lock_version BIGINT NOT NULL DEFAULT 0 COMMENT '状态条件更新版本',
 PRIMARY KEY(tenant_id,order_id,campaign_id),
 UNIQUE KEY uk_marketing_execution_grant(tenant_id,grant_id),
 KEY ix_marketing_execution_campaign(tenant_id,campaign_id,created_at,order_id),
 CONSTRAINT ck_marketing_execution_version CHECK(campaign_version>0 AND lock_version>=0),
 CONSTRAINT ck_marketing_execution_rule CHECK((rule_id IS NULL AND rule_version IS NULL) OR (rule_id IS NOT NULL AND rule_version>0)),
 CONSTRAINT ck_marketing_execution_audience CHECK((audience_id IS NULL AND audience_version IS NULL) OR (audience_id IS NOT NULL AND audience_version>0)),
 CONSTRAINT ck_marketing_execution_benefit CHECK((benefit_id IS NULL AND benefit_version IS NULL AND grant_id IS NULL) OR (benefit_id IS NOT NULL AND benefit_version>0 AND grant_id IS NOT NULL)),
 CONSTRAINT ck_marketing_execution_amount CHECK(discount_amount>0),
 CONSTRAINT ck_marketing_execution_status CHECK(status IN ('RESERVED','GRANT_REQUESTED','GRANTED','APPLIED','RELEASED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='真实订单活动参与及固定版本和权益结果审计';
