-- 仅登记已批准DASHBOARD独立族，不自动接管任何实际租户。
ALTER TABLE employee_authority_route DROP CHECK ck_employee_family,
 ADD CONSTRAINT ck_employee_family CHECK(family IN ('INVENTORY','DIRECTORY','MEMBER_PROFILE','MEMBER_GROWTH','MEMBER_TAG','MEMBER_BEHAVIOR','MEMBER_CYCLE','CYCLE_BENEFIT','MEMBER_POINTS','POINT_OFFER','COUPON_DEFINITION','ENTITLEMENT_DEFINITION','ENTITLEMENT','RULE','AUDIENCE','CAMPAIGN','SEGMENT','COUPON_DELIVERY','JOURNEY','MARKETING_REPORT','ORDER','PAYMENT','FULFILLMENT','AFTERSALE','REFUND','OPS_PAGE','EVENT','RUNTIME','DASHBOARD')),
 MODIFY family VARCHAR(40) NOT NULL COMMENT '独立员工能力族，含独立Dashboard完整租户短集合能力';
