import { navigate } from "./navigation";
import { test, expect, type Page } from "@playwright/test";
import { readFileSync } from "node:fs";
const access=JSON.parse(readFileSync(new URL("../../.local/member-suite-access.json",import.meta.url),"utf8"));
const evidence=process.env.COMMERCE_EVIDENCE_DIR??"../.local/member-suite-evidence";
async function login(page:Page,admin:boolean){await page.goto("/");await page.getByLabel("访问凭据",{exact:true}).fill(admin?access.adminToken:access.journeyToken);await page.getByRole("button",{name:"进入平台",exact:true}).click();}
async function submit(page:Page){await page.getByRole("button",{name:"确认提交",exact:true}).click();}
test("商品经营：类目模板、固定规格、展示图片条码及会员筛选",async({page,browser})=>{
 const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));
 await login(page,true);await navigate(page, "商品管理");await page.getByRole("tab",{name:"类目与模板",exact:true}).click();
 await page.getByRole("button",{name:"创建类目",exact:true}).click();await page.getByLabel("类目标识",{exact:true}).fill("ui-coffee");await page.getByLabel("类目名称",{exact:true}).fill("手冲咖啡");await submit(page);await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page.getByRole("row").filter({hasText:"ui-coffee"})).toBeVisible();
 await page.getByRole("tab",{name:"规格模板",exact:true}).click();await page.getByRole("button",{name:"创建规格模板",exact:true}).click();await page.getByLabel("模板标识",{exact:true}).fill("ui-roast");await page.getByLabel("模板名称",{exact:true}).fill("手冲烘焙模板");await page.getByLabel("属性与允许值",{exact:true}).fill("烘焙=轻烘,中烘");await submit(page);await expect(page.getByRole("dialog")).toHaveCount(0);
 await page.getByRole("tab",{name:"商品资料（SPU）",exact:true}).click();await page.getByRole("button",{name:"创建商品",exact:true}).click();for(const [label,value]of[["商品标识","ui-filter-coffee"],["商品名称","手冲风味咖啡"],["分类","咖啡"],["品牌","日常品牌"]])await page.getByLabel(label,{exact:true}).fill(value);await submit(page);await expect(page.getByRole("dialog")).toHaveCount(0);
 await page.getByRole("row").filter({hasText:"ui-filter-coffee"}).getByRole("button",{name:"展示资料",exact:true}).click();await page.getByRole("button",{name:"编辑展示资料",exact:true}).click();
 for(const [label,value]of[["绑定类目标识","ui-coffee"],["绑定模板标识","ui-roast"],["绑定模板版本","1"],["商品详细说明","轻烘焙手冲风味，适合慢慢品尝。"],["商品图片","/media/coffee.svg|手冲咖啡包装"],["展示资料变更原因","新商品经营资料"]])await page.getByLabel(label,{exact:true}).fill(value);await submit(page);await expect(page.getByRole("button",{name:"编辑展示资料",exact:true})).toBeVisible();await expect(page.getByRole("dialog")).toHaveCount(1);await page.getByRole("button",{name:"关闭",exact:true}).click();
 await page.getByRole("tab",{name:"销售规格与上下架",exact:true}).click();await page.getByRole("button",{name:"创建销售规格",exact:true}).click();for(const[label,value]of[["SKU标识","ui-light-coffee"],["所属商品标识（SPU）","ui-filter-coffee"],["销售名称","轻烘手冲咖啡"],["售价（元）","42.00"]])await page.getByLabel(label,{exact:true}).fill(value);
 await page.getByLabel("规格：烘焙",{exact:true}).click();await page.locator(".ant-select-item-option-content").filter({hasText:/^轻烘$/}).click();await page.getByRole("button",{name:"保存销售规格",exact:true}).click();await expect(page.getByRole("dialog")).toHaveCount(0);
 const sku=page.getByRole("row").filter({hasText:"ui-light-coffee"});await sku.getByRole("button",{name:"条码资料",exact:true}).click();await page.getByRole("button",{name:"维护条码",exact:true}).click();await page.getByLabel("经营条码",{exact:true}).fill("FILTER-042");await page.getByLabel("条码变更原因",{exact:true}).fill("新品条码");await submit(page);await expect(page.getByRole("dialog")).toHaveCount(1);await expect(page.getByText("当前条码：FILTER-042",{exact:true})).toBeVisible();await page.getByRole("button",{name:"关闭",exact:true}).click();
 await sku.getByRole("button",{name:"调价 / 上下架",exact:true}).click();await page.getByLabel("销售状态",{exact:true}).click();await page.locator(".ant-select-item-option-content").filter({hasText:/^上架$/}).click();await page.getByLabel("修订原因",{exact:true}).fill("新品上架");await submit(page);await expect(page.getByRole("dialog")).toHaveCount(0);await page.screenshot({path:`${evidence}/catalog-operations.png`,fullPage:true});
 const member=await browser.newPage();member.on("pageerror",error=>errors.push(error.message));await login(member,false);await member.getByLabel("商品名称或条码",{exact:true}).fill("filter-042");await member.getByRole("button",{name:"筛选商品",exact:true}).click();await expect(member.locator(".product-card")).toHaveCount(1);await expect(member.locator(".product-card")).toContainText("轻烘手冲咖啡");await expect.poll(()=>member.locator(".product-card .product-art img").evaluate((image:HTMLImageElement)=>{const outer=image.parentElement!.getBoundingClientRect(),inner=image.getBoundingClientRect();return image.complete&&image.naturalWidth>0&&inner.bottom<=outer.bottom+1&&inner.top>=outer.top-1;})).toBe(true);await member.getByRole("button",{name:"查看商品",exact:true}).click();await expect(member.getByRole("dialog")).toContainText("手冲咖啡");await expect(member.getByRole("dialog")).toContainText("轻烘焙手冲风味，适合慢慢品尝。");await expect(member.getByRole("img",{name:"手冲咖啡包装",exact:true}).last()).toBeVisible();await expect.poll(()=>member.getByRole("img",{name:"手冲咖啡包装",exact:true}).last().evaluate((image:HTMLImageElement)=>image.complete&&image.naturalWidth>0)).toBe(true);await member.screenshot({path:`${evidence}/catalog-member-detail.png`,fullPage:true});await member.close();expect(errors).toEqual([]);
});
