import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";
const access=JSON.parse(readFileSync(new URL("../../.local/member-suite-access.json",import.meta.url),"utf8"));
const evidence=process.env.COMMERCE_EVIDENCE_DIR??"../.local/member-suite-evidence";
test("经营计划：固定版本调价、逐项回执和渠道价历史",async({page})=>{
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));await page.goto("/");await page.getByLabel("访问凭据",{exact:true}).fill(access.adminToken);await page.getByRole("button",{name:"进入平台",exact:true}).click();await page.getByRole("menuitem",{name:"商品管理",exact:true}).click();
 const sku=page.getByRole("row").filter({hasText:"schedule-coffee"});await sku.getByRole("checkbox").check();await page.getByRole("button",{name:"创建批量计划",exact:true}).click();await page.getByLabel("计划名称",{exact:true}).fill("周末咖啡经营计划");await page.getByLabel("经营原因",{exact:true}).fill("周末经营调价");await page.getByLabel("渠道经营咖啡目标价格",{exact:true}).fill("27.00");await page.getByRole("button",{name:"确认提交",exact:true}).click();await expect(page.getByRole("dialog")).toHaveCount(0);
 await page.getByRole("tab",{name:"批量定时计划",exact:true}).click();await expect(page.getByRole("row").filter({hasText:"周末咖啡经营计划"})).toContainText("待执行");await page.getByRole("button",{name:"推进一批",exact:true}).click();const job=page.getByRole("row").filter({hasText:"周末咖啡经营计划"});await expect(job).toContainText("成功 1");await job.getByRole("button",{name:"逐项回执",exact:true}).click();await expect(page.getByRole("dialog")).toContainText("已执行");await page.screenshot({path:`${evidence}/catalog-job-receipts.png`,fullPage:true});await page.getByRole("button",{name:"关闭",exact:true}).click();
 await page.getByRole("tab",{name:"销售规格与上下架",exact:true}).click();await page.getByRole("button",{name:"刷新",exact:true}).click();await expect(sku).toContainText("¥27.00");await sku.getByRole("button",{name:"渠道价",exact:true}).click();await page.getByRole("button",{name:"设置小程序价",exact:true}).click();await page.getByLabel("渠道售价（元）",{exact:true}).fill("19.00");await page.getByLabel("变更原因",{exact:true}).fill("小程序会员专享价格");await page.getByRole("button",{name:"确认提交",exact:true}).click();await expect(page.getByRole("dialog")).toHaveCount(1);await expect(page.getByRole("dialog")).toContainText("¥19.00 · v1");await page.getByRole("button",{name:"查看小程序价历史",exact:true}).click();await expect(page.getByRole("dialog")).toContainText("小程序会员专享价格");await page.screenshot({path:`${evidence}/catalog-channel-price.png`,fullPage:true});expect(errors).toEqual([]);
});
